"""Generate the JavaScript constants and the parity fixtures of the browser demo.

    uv run python scripts/export_web_assets.py [--model asl=models/<run>/best.pt ...]

- ``app/web/js/landmarks.js``: unified subset, mirror permutation and skeleton edges
- ``tests/fixtures/js_parity.json``: raw sequences + expected ``preprocess()`` outputs
- with ``--model``: ``app/web/models/<id>/`` (INT8 ONNX, labels, preprocessing config) and
  ``app/web/models/index.json``
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import numpy as np

from signrec import landmarks as lm
from signrec.preprocess import PreprocessConfig, mirror, preprocess
from signrec.splits import load_split, split_indices
from signrec.store import PackedDataset

ROOT = Path(__file__).resolve().parents[1]


def landmarks_js() -> str:
    groups = [{"name": n, "source": s, "indices": list(i)} for n, s, i in lm.GROUPS]
    slices = {k: [v.start, v.stop] for k, v in lm.SLICES.items()}
    body = {
        "N_LANDMARKS": lm.N_LANDMARKS,
        "GROUPS": groups,
        "SLICES": slices,
        "POSE_POS": lm.POSE_POS,
        "MIRROR": lm.mirror_permutation(),
        "EDGES": [list(e) for e in lm.skeleton_edges()],
    }
    lines = ["// Generated by scripts/export_web_assets.py from src/signrec/landmarks.py."]
    for k, v in body.items():
        lines.append(f"export const {k} = {json.dumps(v)};")
    return "\n".join(lines) + "\n"


def _seq(rng: np.random.Generator, T: int) -> np.ndarray:
    seq = (0.5 + 0.08 * rng.standard_normal((T, lm.N_LANDMARKS, 3))).astype(np.float32)
    seq[:, lm.POSE_POS["l_shoulder"], :2] = [0.66, 0.62]
    seq[:, lm.POSE_POS["r_shoulder"], :2] = [0.34, 0.61]
    seq += 0.01 * np.cumsum(rng.standard_normal((T, 1, 3)), axis=0).astype(np.float32)
    return seq


def fixtures() -> list[dict]:
    rng = np.random.default_rng(42)
    cases = []

    def add(name: str, seq: np.ndarray, cfg: PreprocessConfig, y_scale: float = 1.0) -> None:
        x, m = preprocess(seq, cfg, y_scale=y_scale)
        cases.append(
            {
                "name": name,
                "cfg": cfg.to_dict(),
                "y_scale": y_scale,
                "shape": list(seq.shape),
                "seq": [None if np.isnan(v) else float(v) for v in seq.ravel()],
                "features": x.ravel().tolist(),
                "mask": m.astype(int).tolist(),
            }
        )

    base = PreprocessConfig()
    s = _seq(rng, 40)
    add("plain", s, base)
    add("webcam_aspect_4_3", s, base, y_scale=0.75)
    add("lsfb_aspect", s, base, y_scale=0.5625)
    s2 = _seq(rng, 37)
    s2[:, lm.SLICES["right_hand"]] = np.nan
    s2[:4, :42] = np.nan
    s2[-3:, :42] = np.nan
    s2[rng.random(s2.shape[:2]) < 0.05] = np.nan
    add("left_dominant_trim_nan", s2, base)
    add("mirrored", mirror(s2), base)
    s3 = _seq(rng, 25)
    s3[:, :42] = np.nan
    add("no_hands", s3, base)
    s4 = _seq(rng, 12)
    s4[:, lm.POSE_POS["l_shoulder"]] = np.nan
    add("no_shoulders_fallback", s4, base)
    add("single_frame", _seq(rng, 1), base)
    add("long", _seq(rng, 150), base)
    add("pad_mode", _seq(rng, 20), PreprocessConfig(length_mode="pad"))
    add("xyz_no_lips_T32", _seq(rng, 50),
        PreprocessConfig(T=32, use_z=True, parts=("left_hand", "right_hand", "pose")))  # fmt: skip
    return cases


MODEL_META = {
    "asl": {
        "name": "ASL (Google ISLR)",
        "short": "ASL",
        "language": "American Sign Language",
        "citation": "Google ISLR, Kaggle 2023",
        "dictionary": "https://www.signasl.org/sign/{gloss}",
    },
    "lsfb": {
        "name": "LSFB (LSFB-ISOL)",
        "short": "LSFB",
        "language": "French Belgian Sign Language",
        "citation": "Fink et al., IJCNN 2021",
        "dictionary": None,
        "examples": "examples/lsfb.json",
        "note": "Glosses of the LSFB corpus (University of Namur).",
    },
}


def easy_signs(model_id: str, k: int = 12, min_support: int = 20) -> list[dict]:
    """The k glosses best recognised on the test set by the deployed run (per-class top-1)."""
    out = ROOT / "app/web/models" / model_id
    run = json.loads((out / "export_report.json").read_text())["run"]
    npz = ROOT / "reports/eval" / f"{run}_test.npz"
    if not npz.exists():
        return []
    labels = json.loads((out / "labels.json").read_text())
    z = np.load(npz)
    y, pred = z["y"], z["probs"].argmax(1)
    scores = [
        (float((pred[y == c] == c).mean()), labels[c])
        for c in range(len(labels))
        if (y == c).sum() >= min_support
    ]
    scores.sort(key=lambda t: -t[0])
    return [{"label": lab, "acc": round(acc, 3)} for acc, lab in scores[:k]]


def package_model(
    model_id: str, ckpt: Path, data: str | None, split: str | None, precision: str = "fp32"
) -> dict:
    """Export a checkpoint for the browser, shipping one precision only.

    FP32 is the default: dynamic INT8 is 3.3x smaller but about 2x slower on CPU / WebAssembly
    for the Conv-Transformer (see reports/latency.json).
    """
    out = ROOT / "app/web/models" / model_id
    cmd = [sys.executable, "-m", "signrec.export", "--ckpt", str(ckpt), "--out", str(out)]
    if data and split:
        cmd += ["--data", data, "--split", split]
    subprocess.run(cmd, cwd=ROOT, check=True)
    other = "int8" if precision == "fp32" else "fp32"
    (out / f"model_{other}.onnx").unlink()
    labels = json.loads((out / "labels.json").read_text())
    return {
        "id": model_id,
        "file": f"model_{precision}.onnx",
        "n_classes": len(labels),
        **MODEL_META[model_id],
    }


def export_examples(n: int, seed: int = 0) -> None:
    """Random LSFB-ISOL test-set clips (CC BY 4.0) replayable in the demo, one per gloss."""
    ds = PackedDataset(ROOT / "data/processed/lsfb_isol")
    rows = split_indices(ds.index, load_split(ROOT / "splits/lsfb_isol_signer.json"))["test"]
    rng = np.random.default_rng(seed)
    picked, seen = [], set()
    for r in rng.permutation(rows):
        label = ds.index.label.iloc[r]
        if label in seen or ds.index.n_frames.iloc[r] < 12:
            continue
        seen.add(label)
        seq = ds.sequence(int(r))
        picked.append(
            {
                "label": label,
                "signer": str(ds.index.signer_id.iloc[r]),
                "fps": float(ds.index.fps.iloc[r]),
                "T": int(seq.shape[0]),
                "data": [None if np.isnan(v) else round(float(v), 4) for v in seq.ravel()],
            }
        )
        if len(picked) == n:
            break
    out = ROOT / "app/web/examples/lsfb.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "source": "LSFB-ISOL v2 test signers (CC BY 4.0)",
        "y_scale": ds.y_scale,
        "clips": picked,
    }
    out.write_text(json.dumps(payload))
    print(f"wrote {len(picked)} examples to {out.relative_to(ROOT)}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", action="append", default=[], help="id=checkpoint (id: asl | lsfb)")
    ap.add_argument("--examples", type=int, default=0, help="number of LSFB example clips")
    ap.add_argument("--precision", choices=["fp32", "int8"], default="fp32")
    a = ap.parse_args()
    if a.examples:
        export_examples(a.examples)
    data = {"asl": ("data/processed/kaggle_asl", "splits/kaggle_asl_signer.json"),
            "lsfb": ("data/processed/lsfb_isol", "splits/lsfb_isol_signer.json")}  # fmt: skip
    index_path = ROOT / "app/web/models/index.json"
    index = json.loads(index_path.read_text())["models"] if index_path.exists() else []
    for spec in a.model:
        mid, ckpt = spec.split("=", 1)
        entry = package_model(mid, ROOT / ckpt, *data[mid], precision=a.precision)
        index = [m for m in index if m["id"] != mid] + [entry]
    if index:
        for m in index:
            m["easy"] = easy_signs(m["id"])
        index.sort(key=lambda m: m["id"])
        index_path.write_text(json.dumps({"models": index}, indent=1, ensure_ascii=False))
    (ROOT / "app/web/js/landmarks.js").write_text(landmarks_js())
    out = ROOT / "tests/fixtures/js_parity.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(fixtures()))
    print(f"wrote app/web/js/landmarks.js and {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
